import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Compass, 
  DollarSign, 
  Clock, 
  Check, 
  X, 
  Sparkles, 
  ArrowRight,
  TrendingUp,
  XCircle,
  Briefcase,
  AlertCircle,
  CloudUpload
} from 'lucide-react';
import Button from '../../components/common/Button';
import { ROUTES } from '../../constants/routes';
import { getUserData } from '../../utils/userStorage';

const RAW_CAREER_PATHWAYS = [
  {
    id: 1,
    role: 'Principal Frontend Architect',
    salary: '$165,000 - $210,000 / yr',
    upskillTime: '3 Months',
    demandGrowth: '+28% YoY Industry Demand Growth',
    requiredSkills: ['React', 'TypeScript', 'Design Systems', 'Web Performance', 'Micro-frontends'],
    overview: 'Lead the architecture of enterprise-scale frontend applications, design reusable design systems, and drive performance optimizations across engineering teams.'
  },
  {
    id: 2,
    role: 'Full-Stack Engineering Lead',
    salary: '$150,000 - $185,000 / yr',
    upskillTime: '5 Months',
    demandGrowth: '+22% YoY Demand',
    requiredSkills: ['React', 'Node.js', 'AWS Cloud', 'Docker', 'System Design'],
    overview: 'Oversee end-to-end software development, manage backend services, orchestrate cloud deployments, and mentor cross-functional engineering teams.'
  },
  {
    id: 3,
    role: 'AI Product Front-End Architect',
    salary: '$170,000 - $220,000 / yr',
    upskillTime: '4 Months',
    demandGrowth: '+45% YoY High-Growth Sector',
    requiredSkills: ['React', 'TypeScript', 'LangChain', 'Python APIs', 'Vector Embeddings'],
    overview: 'Pioneer the creation of intuitive user interfaces for generative AI applications, vector database interactions, and LLM-powered enterprise tooling.'
  }
];

const CareerRecommendations = () => {
  const navigate = useNavigate();
  const [selectedRole, setSelectedRole] = useState(null);
  const [userSkills, setUserSkills] = useState(() => getUserData('skills', []) || []);

  useEffect(() => {
    const handleUpdate = () => {
      setUserSkills(getUserData('skills', []) || []);
    };
    window.addEventListener('skillsUpdated', handleUpdate);
    window.addEventListener('userDataChanged', handleUpdate);
    return () => {
      window.removeEventListener('skillsUpdated', handleUpdate);
      window.removeEventListener('userDataChanged', handleUpdate);
    };
  }, []);

  const hasSkills = userSkills.length > 0;

  const pathways = RAW_CAREER_PATHWAYS.map(path => {
    const evaluatedSkills = path.requiredSkills.map(skillName => {
      const possessed = userSkills.some(s => {
        const sName = (s.name || s.skill_name || '').toLowerCase();
        const target = skillName.toLowerCase();
        return sName.includes(target) || target.includes(sName);
      });
      return { name: skillName, possessed };
    });

    const possessedCount = evaluatedSkills.filter(s => s.possessed).length;
    const matchScore = hasSkills ? Math.round((possessedCount / evaluatedSkills.length) * 100) : 0;
    const aiConfidence = hasSkills ? `${Math.min(98, Math.max(70, matchScore + 10))}% AI Confidence` : 'Pending Skills Data';

    return {
      ...path,
      matchScore,
      aiConfidence,
      requiredSkills: evaluatedSkills
    };
  });

  return (
    <div className="space-y-8 pb-12 animate-fade-in">
      {/* Header Banner */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-gradient-to-r from-teal-600/10 via-emerald-600/10 to-teal-500/10 dark:from-teal-900/30 dark:via-emerald-950/40 dark:to-teal-900/20 p-6 rounded-3xl border border-teal-500/20 dark:border-teal-500/30">
        <div className="space-y-1">
          <h1 className="text-xl md:text-2xl font-black text-slate-900 dark:text-white flex items-center gap-2.5">
            <Compass className="w-7 h-7 text-teal-500 dark:text-teal-400 stroke-[2.4]" />
            AI Career Pathway & Role Recommendations
          </h1>
          <p className="text-xs font-medium text-slate-600 dark:text-slate-300">
            Tailored career advancement paths generated by analyzing your skill telemetry and industry growth data.
          </p>
        </div>
      </div>

      {!hasSkills && (
        <div className="p-5 rounded-2xl bg-amber-500/10 border border-amber-500/30 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <AlertCircle className="w-6 h-6 text-amber-500 shrink-0" />
            <div>
              <p className="text-xs font-bold text-slate-900 dark:text-white">
                No verified skills detected in your profile
              </p>
              <p className="text-[11px] text-slate-500 dark:text-slate-400 mt-0.5">
                Upload your resume or add your skills in Skills Management to generate accurate AI role matching.
              </p>
            </div>
          </div>
          <button
            onClick={() => navigate(ROUTES.RESUME_UPLOAD)}
            className="px-4 py-2 bg-amber-500 hover:bg-amber-600 text-slate-950 rounded-xl text-xs font-bold shrink-0 flex items-center gap-1.5 transition-colors cursor-pointer"
          >
            <CloudUpload className="w-4 h-4" />
            Upload Resume
          </button>
        </div>
      )}

      {/* 3 Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {pathways.map((path) => (
          <div
            key={path.id}
            className="p-6 bg-white dark:bg-[#161f33] text-slate-900 dark:text-white border border-slate-200/90 dark:border-slate-800 rounded-3xl shadow-xl hover:shadow-2xl transition-all duration-300 flex flex-col justify-between space-y-6"
          >
            <div className="space-y-5">
              {/* Top Header Row: Match Pill & AI Confidence */}
              <div className="flex items-center justify-between">
                <span className="px-3 py-1 rounded-full text-xs font-extrabold bg-teal-500/15 text-teal-600 dark:text-teal-400 border border-teal-500/30">
                  {path.matchScore}% Match
                </span>
                <span className="text-[11px] font-semibold text-slate-400 dark:text-slate-400">
                  {path.aiConfidence}
                </span>
              </div>

              {/* Role Title & Salary */}
              <div className="space-y-1">
                <h2 className="text-lg font-black tracking-tight text-slate-900 dark:text-white leading-snug min-h-[3rem] flex items-center">
                  {path.role}
                </h2>
                <div className="flex items-center gap-1 text-teal-600 dark:text-teal-400 font-extrabold text-sm">
                  <DollarSign className="w-4 h-4 shrink-0 -mr-1" />
                  <span>{path.salary}</span>
                </div>
              </div>

              {/* Upskill Time & YoY Growth Box */}
              <div className="p-4 bg-slate-50 dark:bg-[#0f1524] rounded-2xl border border-slate-200/80 dark:border-[#2b3854] space-y-1.5">
                <div className="flex items-center gap-2 text-xs font-bold text-slate-700 dark:text-slate-200">
                  <Clock className="w-4 h-4 text-teal-500 shrink-0" />
                  <span>Estimated Upskill Time: <strong className="text-slate-900 dark:text-white">{path.upskillTime}</strong></span>
                </div>
                <div className="text-[11px] font-extrabold text-teal-600 dark:text-teal-400 pl-6">
                  {path.demandGrowth}
                </div>
              </div>

              {/* Required Skills Section */}
              <div className="space-y-2.5">
                <h4 className="text-[11px] font-black tracking-wider uppercase text-slate-400 dark:text-slate-400">
                  REQUIRED SKILLS
                </h4>
                <div className="flex flex-wrap gap-2">
                  {path.requiredSkills.map((skill, idx) => (
                    <span
                      key={idx}
                      className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-xl text-xs font-bold transition-all ${
                        skill.possessed
                          ? 'bg-teal-50 dark:bg-teal-950/40 text-teal-700 dark:text-teal-400 border border-teal-200 dark:border-teal-800/60'
                          : 'bg-rose-50 dark:bg-rose-950/40 text-rose-700 dark:text-rose-400 border border-rose-200 dark:border-rose-800/60'
                      }`}
                    >
                      {skill.possessed ? (
                        <Check className="w-3.5 h-3.5 stroke-[2.5]" />
                      ) : (
                        <X className="w-3.5 h-3.5 stroke-[2.5]" />
                      )}
                      {skill.name}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Footer Action Buttons */}
            <div className="grid grid-cols-2 gap-3 pt-4 border-t border-slate-100 dark:border-slate-800/80">
              <button
                onClick={() => setSelectedRole(path)}
                className="w-full py-2.5 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-xl text-xs font-extrabold transition-all cursor-pointer"
              >
                View Details
              </button>
              <button
                onClick={() => navigate(ROUTES.LEARNING_PATH)}
                className="w-full py-2.5 bg-teal-600 hover:bg-teal-700 text-white rounded-xl text-xs font-extrabold shadow-md shadow-teal-600/30 transition-all cursor-pointer flex items-center justify-center gap-1"
              >
                <span>Start Pathway</span>
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Role Details Modal */}
      {selectedRole && (
        <div className="fixed inset-0 z-50 bg-slate-950/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="w-full max-w-lg rounded-3xl p-6 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-2xl space-y-6 animate-scale-up">
            <div className="flex items-start justify-between pb-4 border-b border-slate-100 dark:border-slate-800">
              <div className="space-y-1">
                <span className="px-3 py-1 rounded-full text-xs font-extrabold bg-teal-500/10 text-teal-600 dark:text-teal-400 border border-teal-500/20">
                  {selectedRole.matchScore}% Match Rate
                </span>
                <h3 className="font-extrabold text-xl text-slate-900 dark:text-white">
                  {selectedRole.role}
                </h3>
              </div>
              <button
                onClick={() => setSelectedRole(null)}
                className="p-1 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 cursor-pointer"
              >
                <XCircle className="w-6 h-6" />
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <h4 className="text-xs font-extrabold uppercase text-slate-400 tracking-wider">Role Overview</h4>
                <p className="text-xs font-medium text-slate-700 dark:text-slate-300 leading-relaxed mt-1">
                  {selectedRole.overview}
                </p>
              </div>

              <div className="p-4 bg-slate-50 dark:bg-slate-800/60 rounded-2xl border border-slate-200 dark:border-slate-700/60 grid grid-cols-2 gap-3 text-xs">
                <div>
                  <span className="text-slate-400 font-bold block text-[10px] uppercase">Average Salary</span>
                  <span className="font-extrabold text-teal-600 dark:text-teal-400">{selectedRole.salary}</span>
                </div>
                <div>
                  <span className="text-slate-400 font-bold block text-[10px] uppercase">Upskill Timeline</span>
                  <span className="font-extrabold text-slate-900 dark:text-white">{selectedRole.upskillTime}</span>
                </div>
              </div>
            </div>

            <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100 dark:border-slate-800">
              <Button variant="outline" onClick={() => setSelectedRole(null)}>
                Close
              </Button>
              <Button
                variant="primary"
                onClick={() => {
                  setSelectedRole(null);
                  navigate(ROUTES.LEARNING_PATH);
                }}
                className="bg-teal-600 hover:bg-teal-700"
              >
                Start Pathway Now
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CareerRecommendations;