import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Compass, 
  DollarSign, 
  Clock, 
  Check, 
  X, 
  Sparkles, 
  ArrowRight,
  TrendingUp,
  XCircle,
  Briefcase
} from 'lucide-react';
import Button from '../../components/common/Button';
import { ROUTES } from '../../constants/routes';

const CAREER_PATHWAYS = [
  {
    id: 1,
    role: 'Principal Frontend Architect',
    matchScore: 94,
    aiConfidence: '96% AI Confidence',
    salary: '$165,000 - $210,000 / yr',
    upskillTime: '3 Months',
    demandGrowth: '+28% YoY Industry Demand Growth',
    requiredSkills: [
      { name: 'React', possessed: true },
      { name: 'TypeScript', possessed: true },
      { name: 'Design Systems', possessed: true },
      { name: 'Web Performance', possessed: true },
      { name: 'Micro-frontends', possessed: false },
    ],
    overview: 'Lead the architecture of enterprise-scale frontend applications, design reusable design systems, and drive performance optimizations across engineering teams.'
  },
  {
    id: 2,
    role: 'Full-Stack Engineering Lead',
    matchScore: 86,
    aiConfidence: '88% AI Confidence',
    salary: '$150,000 - $185,000 / yr',
    upskillTime: '5 Months',
    demandGrowth: '+22% YoY Demand',
    requiredSkills: [
      { name: 'React', possessed: true },
      { name: 'Node.js', possessed: true },
      { name: 'AWS Cloud', possessed: false },
      { name: 'Docker', possessed: true },
      { name: 'System Design', possessed: false },
    ],
    overview: 'Oversee end-to-end software development, manage backend services, orchestrate cloud deployments, and mentor cross-functional engineering teams.'
  },
  {
    id: 3,
    role: 'AI Product Front-End Architect',
    matchScore: 82,
    aiConfidence: '85% AI Confidence',
    salary: '$170,000 - $220,000 / yr',
    upskillTime: '4 Months',
    demandGrowth: '+45% YoY High-Growth Sector',
    requiredSkills: [
      { name: 'React', possessed: true },
      { name: 'TypeScript', possessed: true },
      { name: 'LangChain', possessed: false },
      { name: 'Python APIs', possessed: true },
      { name: 'Vector Embeddings', possessed: true },
    ],
    overview: 'Pioneer the creation of intuitive user interfaces for generative AI applications, vector database interactions, and LLM-powered enterprise tooling.'
  }
];

const CareerRecommendations = () => {
  const navigate = useNavigate();
  const [selectedRole, setSelectedRole] = useState(null);

  return (
    <div className="space-y-8 pb-12 animate-fade-in">
      {/* Header Banner */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-gradient-to-r from-blue-600/10 via-teal-600/10 to-indigo-600/10 dark:from-blue-500/20 dark:via-teal-500/20 dark:to-indigo-500/20 p-6 rounded-3xl border border-blue-500/20 dark:border-blue-500/30">
        <div className="space-y-1">
          <h1 className="text-xl md:text-2xl font-black text-slate-900 dark:text-white flex items-center gap-2.5">
            <Compass className="w-7 h-7 text-emerald-500 dark:text-emerald-400 stroke-[2.4]" />
            AI Career Pathway & Role Recommendations
          </h1>
          <p className="text-xs font-medium text-slate-600 dark:text-slate-300">
            Tailored career advancement paths generated by analyzing your skill telemetry and industry growth data.
          </p>
        </div>
      </div>

      {/* 3 Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {CAREER_PATHWAYS.map((path) => (
          <div
            key={path.id}
            className="p-6 bg-white dark:bg-[#161f33] text-slate-900 dark:text-white border border-slate-200/90 dark:border-slate-800 rounded-3xl shadow-xl hover:shadow-2xl transition-all duration-300 flex flex-col justify-between space-y-6"
          >
            <div className="space-y-5">
              {/* Top Header Row: Match Pill & AI Confidence */}
              <div className="flex items-center justify-between">
                <span className="px-3 py-1 rounded-full text-xs font-extrabold bg-emerald-500/15 text-emerald-600 dark:text-emerald-400 border border-emerald-500/30">
                  {path.matchScore}% Match
                </span>
                <span className="text-[11px] font-semibold text-slate-400 dark:text-slate-400">
                  {path.aiConfidence}
                </span>
              </div>

              {/* Role Title & Salary */}
              <div className="space-y-1">
                <h2 className="text-lg font-black tracking-tight text-slate-900 dark:text-white leading-snug min-h-[3rem] flex items-center">
                  {path.role}
                </h2>
                <div className="flex items-center gap-1 text-emerald-600 dark:text-emerald-400 font-extrabold text-sm">
                  <DollarSign className="w-4 h-4 shrink-0 -mr-1" />
                  <span>{path.salary}</span>
                </div>
              </div>

              {/* Upskill Time & YoY Growth Box */}
              <div className="p-4 bg-slate-50 dark:bg-[#0f1524] rounded-2xl border border-slate-200/80 dark:border-[#2b3854] space-y-1.5">
                <div className="flex items-center gap-2 text-xs font-bold text-slate-700 dark:text-slate-200">
                  <Clock className="w-4 h-4 text-blue-500 shrink-0" />
                  <span>Estimated Upskill Time: <strong className="text-slate-900 dark:text-white">{path.upskillTime}</strong></span>
                </div>
                <div className="text-[11px] font-extrabold text-emerald-600 dark:text-emerald-400 pl-6">
                  {path.demandGrowth}
                </div>
              </div>

              {/* Required Skills Section */}
              <div className="space-y-2.5">
                <h4 className="text-[11px] font-black tracking-wider uppercase text-slate-400 dark:text-slate-400">
                  REQUIRED SKILLS
                </h4>
                <div className="flex flex-wrap gap-2">
                  {path.requiredSkills.map((skill, idx) => (
                    <span
                      key={idx}
                      className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-xl text-xs font-bold transition-all ${
                        skill.possessed
                          ? 'bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800/60'
                          : 'bg-rose-50 dark:bg-rose-950/40 text-rose-700 dark:text-rose-400 border border-rose-200 dark:border-rose-800/60'
                      }`}
                    >
                      {skill.possessed ? (
                        <Check className="w-3.5 h-3.5 stroke-[2.5]" />
                      ) : (
                        <X className="w-3.5 h-3.5 stroke-[2.5]" />
                      )}
                      {skill.name}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Footer Action Buttons */}
            <div className="grid grid-cols-2 gap-3 pt-4 border-t border-slate-100 dark:border-slate-800/80">
              <button
                onClick={() => setSelectedRole(path)}
                className="w-full py-2.5 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-xl text-xs font-extrabold transition-all cursor-pointer"
              >
                View Details
              </button>
              <button
                onClick={() => navigate(ROUTES.LEARNING_PATH)}
                className="w-full py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-extrabold shadow-md shadow-blue-600/30 transition-all cursor-pointer flex items-center justify-center gap-1"
              >
                <span>Start Pathway</span>
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Role Details Modal */}
      {selectedRole && (
        <div className="fixed inset-0 z-50 bg-slate-950/60 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="w-full max-w-lg rounded-3xl p-6 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-2xl space-y-6 animate-scale-up">
            <div className="flex items-start justify-between pb-4 border-b border-slate-100 dark:border-slate-800">
              <div className="space-y-1">
                <span className="px-3 py-1 rounded-full text-xs font-extrabold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20">
                  {selectedRole.matchScore}% Match Rate
                </span>
                <h3 className="font-extrabold text-xl text-slate-900 dark:text-white">
                  {selectedRole.role}
                </h3>
              </div>
              <button
                onClick={() => setSelectedRole(null)}
                className="p-1 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 cursor-pointer"
              >
                <XCircle className="w-6 h-6" />
              </button>
            </div>

            <div className="space-y-4">
              <div>
                <h4 className="text-xs font-extrabold uppercase text-slate-400 tracking-wider">Role Overview</h4>
                <p className="text-xs font-medium text-slate-700 dark:text-slate-300 leading-relaxed mt-1">
                  {selectedRole.overview}
                </p>
              </div>

              <div className="p-4 bg-slate-50 dark:bg-slate-800/60 rounded-2xl border border-slate-200 dark:border-slate-700/60 grid grid-cols-2 gap-3 text-xs">
                <div>
                  <span className="text-slate-400 font-bold block text-[10px] uppercase">Average Salary</span>
                  <span className="font-extrabold text-emerald-600 dark:text-emerald-400">{selectedRole.salary}</span>
                </div>
                <div>
                  <span className="text-slate-400 font-bold block text-[10px] uppercase">Upskill Timeline</span>
                  <span className="font-extrabold text-slate-900 dark:text-white">{selectedRole.upskillTime}</span>
                </div>
              </div>
            </div>

            <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100 dark:border-slate-800">
              <Button variant="outline" onClick={() => setSelectedRole(null)}>
                Close
              </Button>
              <Button
                variant="primary"
                onClick={() => {
                  setSelectedRole(null);
                  navigate(ROUTES.LEARNING_PATH);
                }}
                className="bg-blue-600 hover:bg-blue-700"
              >
                Start Pathway Now
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CareerRecommendations;