# Generated by Django 5.2.17 on 2026-08-08 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(default='San Francisco, CA', max_length=150)),
                ('experience_years', models.IntegerField(default=3)),
                ('education', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, default='Passionate Web Architect & Developer.', null=True)),
                ('linkedin', models.URLField(blank=True, max_length=500, null=True)),
                ('github', models.URLField(blank=True, max_length=500, null=True)),
                ('portfolio', models.URLField(blank=True, max_length=500, null=True)),
                ('readiness_score', models.IntegerField(default=84)),
                ('resume_completion_score', models.IntegerField(default=90)),
                ('profile_completion_score', models.IntegerField(default=85)),
                ('certifications_json', models.JSONField(blank=True, default=list)),
                ('projects_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('duration', models.CharField(blank=True, default='2023 - Present', max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
